### ISSUE TITLE
File uploads

### ISSUE THREAD

**Issue by stefreak** [osiloke/mezzanine_widgets#6]
when using the file upload form fields (option_fields.py) we encountered problems using it.

we couldn't find the file anywhere in MEDIA_ROOT after uploading it into the widget and in the database only the original filename was saved.

Did I do something wrong, is this a feature that is not yet implemented correctly, or is it a bug? I would happily provide a patch for it to work the way I would like it with maybe a little guidance.

thanks
steffen

**Comment by stefreak** [comment]
ok, the current state of my investigation is that the `WidgetOptionEntry` class should dynamically use a different database field type for a given field type (`option_fields.py`). That would require to store the field type number in the database too.

I'm trying to implement this at the moment, please correct me if this would not be a viable solution.

regards
steffen

**Comment by osiloke** [comment]
In hindsight, i should have taken out the File option fields since i hadn't updated the view's logic to parse files properly. You probably want to store the widget option type as a content type (I actually did this previously). 
Rather than store widget option field type in the database, you can use a WidgetModel to upload files. You can create a new WidgetModel that has a file field. I will probably update the views logic to handle files differently.

Here's an example from another project i have.

``` python
class PhotoWidget(WidgetClassBase):
    template = "widgets/photo.html"
    model = ImageModel
    single = True
    editableFields = "file,description"
    model_template = ""

    def render(self, context, **kwargs):
        context.update({'query_set': kwargs.get("queryset", None), 'model': self.model})
        return context

    class Meta:
        name = _("Photo")
        author = 'Progweb Team'
```

``` html
{% load i18n mezzanine_tags frontend_tags %}
{% if query_set %}
{% with query_set as object %}
    {% can_edit object file %}{% endcan_edit %}
    {% if "uploads/non.jpg" == object.file %}
    {% else %}
    <img src="{{ object.file.url }}" />
    {% endif %}
{%  endwith %}
{% else %}
<div class="placeholder">
    <h3>Edit this Widget to add a Photo</h3>
</div>
{% endif %} 
```

ImageModel is just a normal django model.

**Comment by stefreak** [comment]
Ahaa, thank you, this makes sense and should provide enough flexibility for me, I'll try it :)
